---
- hosts: localhost
  sudo: yes
  tasks:
  - name: apt-get update
    apt: update_cache=yes

  - name: install base
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - default-jdk
      - default-jre
      - git
      - libicu48
      - make
      - python
      - python-setuptools
      - python-software-properties
      - ruby1.9.1
      - ruby1.9.1-dev
      - rubygems1.9.1
      - irb1.9.1
      - ri1.9.1
      - rdoc1.9.1
      - unzip
      - zip
      - sqlite3
      - libsqlite3-dev
      - gawk

  - name: set ruby version to 1.9.1
    command: update-alternatives --set ruby /usr/bin/ruby1.9.1

  - name: set gem version to 1.9.1
    command: update-alternatives --set gem /usr/bin/gem1.9.1

  - name: install node apt repo
    apt_repository: repo=ppa:chris-lea/node.js state=present

  - name: install node
    apt: pkg=nodejs state=present update_cache=yes

  - name: install global node modules
    apt: name={{ item }} state=present global=yes
    with_items:
      - bower
      - grunt-cli
      - node-sass
      - uglify-js
      - phantomjs

  - name: install bundler
    gem: name=bundler state=latest user_install=no

  - name: mongodb | get 10gen apt key
    apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

  - name: mongodb | get 10gen apt repository
    copy: src=files/apt-source-mongodb dest=/etc/apt/sources.list.d/10gen.list mode=755

  - name: mongodb | install
    apt: pkg=mongodb-10gen=2.4.10 state=installed update_cache=yes

  - name: install php55 apt repo
    apt_repository: repo=ppa:ondrej/php5 state=present

  - name: install php5.5
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - php5
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-intl
      - php5-mysql
      - php5-mcrypt
      - php5-xdebug
      - php5-xsl
      - php-apc
      - php-codesniffer
      - php-pear
      - php5-sqlite

  - name: install composer globally
    raw: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin

  - name: link create composer symlink
    file: src=/usr/local/bin/composer.phar dest=/usr/local/bin/composer state=link

  - name: update composer
    command: composer self-update

  - name: install phpunit
    get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=755

  - name: check for mongo php extension
    shell: pecl list | grep mongo
    register: pecl_mongo_exists
    ignore_errors: True

  - name: install mongo php extension
    raw: printf "\n" | sudo pecl install mongo
    when: pecl_mongo_exists|failed

  - name: configure mongo extension
    copy: src=files/mongo.ini dest=/etc/php5/mods-available

  - name: enable mongoDB php driver
    command: php5enmod mongo

  - name: check for sqlite php extension
    shell: pecl list | grep sqlite
    register: pecl_sqlite_exists
    ignore_errors: True

  - name: install sqlite php extension
    raw: printf "\n" | sudo pecl install sqlite
    when: pecl_sqlite_exists|failed
