---
- hosts: localhost
  sudo: yes
  tasks:
  - name: apt-get update
    apt: update_cache=yes

  - name: install base
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
      - make
      - python
      - python-setuptools
      - python-software-properties
      - rubygems
      - unzip
      - zip
      - libicu48
      - default-jre
      - default-jdk
      - mysql-server
      - mysql-client

  - name: install node apt repo
    apt_repository: repo=ppa:chris-lea/node.js state=present

  - name: install node
    apt: pkg=nodejs state=present update_cache=yes

  - name: install bower
    npm: name=bower state=present global=yes

  - name: install grunt
    npm: name=grunt-cli state=present global=yes

  - name: install phantomjs
    npm: name=phantomjs state=present global=yes

  - name: install bundler
    gem: name=bundler state=latest user_install=no

  - name: mongodb | get 10gen apt key
    apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

  - name: mongodb | get 10gen apt repository
    copy: src=files/apt-source-mongodb dest=/etc/apt/sources.list.d/10gen.list mode=755

  - name: mongodb | install
    apt: pkg=mongodb-10gen=2.4.10 state=installed update_cache=yes

  - name: install php55 apt repo
    apt_repository: repo=ppa:ondrej/php5 state=present

  - name: install php5.5
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - php5
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-intl
      - php5-mysql
      - php5-mcrypt
      - php5-xdebug
      - php5-xsl
      - php-apc
      - php-codesniffer
      - php-pear

  - name: install composer globally
    raw: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin

  - name: link create composer symlink
    file: src=/usr/local/bin/composer.phar dest=/usr/local/bin/composer state=link

  - name: update composer
    command: composer self-update

  - name: install phpunit
    get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=755

  - name: check for mongo php extension
    shell: pecl list | grep mongo
    register: pecl_mongo_exists
    ignore_errors: True

  - name: install mongo php extension
    raw: printf "\n" | sudo pecl install mongo
    when: pecl_mongo_exists|failed

  - name: configure mongo extension
    copy: src=files/mongo.ini dest=/etc/php5/mods-available

  - name: enable mongoDB php driver
    command: php5enmod mongo
